describe('login', () => {
  beforeEach(() => {
    cy.safeVisit('https://www.test.smartfunding.co.il/')
  })

  it('correct login', () => {
    cy.get('a.links__link.\\33 21').click()
    cy.get('.modal-header', { timeout: 10000 })
      .should('be.visible')
    cy.get('.modal-body', { timeout: 10000 })
      .should('be.visible')
    cy.get('.login-form > [name="email"]')
      .type("army7makarova@gmail.com")
    cy.get('[name="password"]')
      .type("Qwerty123")
    cy.get('.modal-form-login-button').click()
    cy.contains('Profile', { timeout: 10000 })
      .should('be.visible')
  })

  it('incorrect input', () => {
    cy.get('a.links__link.\\33 21').click()
    cy.get('.modal-header', { timeout: 10000 }).should('be.visible')
    cy.get('.modal-body', { timeout: 10000 }).should('be.visible')
    cy.get('.modal-form-login-button').click()
    cy.get('#התחברות span:nth-child(2)')
      .contains('Cannot be empty')
      .should('be.visible')
    cy.get('#התחברות span:nth-child(4)')
      .contains('Cannot be empty')
      .should('be.visible')
    cy.get('.login-form > [name="email"]').type("mmm")
    cy.get('[name="password"]').type("Qwe")
    cy.get('#התחברות span:nth-child(2)')
      .contains('Incorrect email')
      .should('be.visible')
    cy.get('#התחברות span:nth-child(4)')
      .contains('Minimal length is 8')
      .should('be.visible')
  })

  it('incorrect email', () => {
    cy.get('a.links__link.\\33 21').click()
    cy.get('.modal-header', { timeout: 10000 }).should('be.visible')
    cy.get('.modal-body', { timeout: 10000 }).should('be.visible')
    cy.get('.login-form > [name="email"]')
      .type("army7makarova@mail.com")
    cy.get('[name="password"]')
      .type("Qwerty123")
    cy.get('.modal-form-login-button').click()
    cy.get('.swal2-popup')
      .should('be.visible')
    cy.get('.swal2-x-mark')
      .should('be.visible')
    cy.get('#swal2-title')
      .contains(/Error|שגיאה/i)
      .should('be.visible')
    cy.get('#swal2-content')
      .contains(/Wrong E-mail or password|אימייל או סיסמה שגויים/i)
      .should('be.visible')
  })

  it('incorrect password', () => {
    cy.get('a.links__link.\\33 21').click()
    cy.get('.modal-header', { timeout: 10000 }).should('be.visible')
    cy.get('.modal-body', { timeout: 10000 }).should('be.visible')
    cy.get('.login-form > [name="email"]')
      .type("army7makarova@gmail.com")
    cy.get('[name="password"]')
      .type("Qwerty333")
    cy.get('.modal-form-login-button').click()
    cy.get('.swal2-popup')
      .should('be.visible')
    cy.get('.swal2-x-mark')
      .should('be.visible')
    cy.get('#swal2-title')
      .should('be.visible')
      .invoke('text')
      .should('match', /Error|שגיאה/i)
    cy.get('#swal2-content')
      .should('be.visible')
      .invoke('text')
      .should('match', /Wrong E-mail or password|אימייל או סיסמה שגויים/i)
  })


  it('forget password', () => {
    cy.get('a.links__link.\\33 21').click()
      .type()
  })



})